conky.config = {
    alignment = 'top_left',
    gap_x = 0, gap_y = 0,
    minimum_width = 1920, maximum_width = 1920,
    minimum_height = 1080,
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    double_buffer = true,
    update_interval = 0.2,
    draw_shades = false,
    lua_load = '/home/arjun/.config/conky/nothing/bg.lua',
    lua_draw_hook_post = 'bg',
}

conky.text = [[]]
